import { DocumentTemplate } from '../types/template';

export const INVOICE_TEMPLATES: DocumentTemplate[] = [
  {
    id: 'inv-classic',
    name: 'Classic Professional',
    type: 'invoice',
    category: 'Classic',
    description: 'Traditional business layout with double borders, clear totals, and signature block.',
    style: 'Classic • Traditional',
    previewColor: '#1e293b',
    layout: {
      headerStyle: 'classic',
      tableStyle: 'bordered',
      totalsStyle: 'box',
      footerStyle: 'simple',
      signaturePlacement: 'bottom-right',
    },
    defaultTheme: {
      primaryColor: '#1e293b',
      secondaryColor: '#64748b',
      textColor: '#0f172a',
      fontFamily: 'Inter',
    },
  },
  {
    id: 'inv-minimal',
    name: 'Minimal White',
    type: 'invoice',
    category: 'Minimal',
    description: 'Extremely clean with high whitespace, thin subtle lines, and elegant typography.',
    style: 'Minimal • Clean',
    previewColor: '#64748b',
    layout: {
      headerStyle: 'minimal',
      tableStyle: 'clean',
      totalsStyle: 'subtle',
      footerStyle: 'simple',
      signaturePlacement: 'bottom-right',
    },
    defaultTheme: {
      primaryColor: '#334155',
      secondaryColor: '#94a3b8',
      textColor: '#1e293b',
      fontFamily: 'Roboto',
    },
  },
  {
    id: 'inv-modern-blue',
    name: 'Modern Blue',
    type: 'invoice',
    category: 'Modern',
    description: 'VISTAAR signature blue header accent with rounded container blocks.',
    style: 'Modern • Corporate',
    previewColor: '#2563eb',
    badgeText: 'Popular',
    layout: {
      headerStyle: 'modern',
      tableStyle: 'striped',
      totalsStyle: 'box',
      footerStyle: 'boxed',
      signaturePlacement: 'bottom-right',
    },
    defaultTheme: {
      primaryColor: '#2563eb',
      secondaryColor: '#3b82f6',
      textColor: '#0f172a',
      fontFamily: 'Poppins',
    },
  },
  {
    id: 'inv-corporate-dark',
    name: 'Corporate Dark',
    type: 'invoice',
    category: 'Corporate',
    description: 'Strong dark header banner with high-contrast corporate typography.',
    style: 'Corporate • Bold',
    previewColor: '#0f172a',
    layout: {
      headerStyle: 'dark-banner',
      tableStyle: 'accent-header',
      totalsStyle: 'bold-banner',
      footerStyle: 'executive',
      signaturePlacement: 'bottom-split',
    },
    defaultTheme: {
      primaryColor: '#0f172a',
      secondaryColor: '#475569',
      textColor: '#0f172a',
      fontFamily: 'Inter',
    },
  },
  {
    id: 'inv-green',
    name: 'Green Business',
    type: 'invoice',
    category: 'Modern',
    description: 'Fresh emerald green accent bars with clean modern section dividers.',
    style: 'Fresh • Eco-friendly',
    previewColor: '#059669',
    layout: {
      headerStyle: 'modern',
      tableStyle: 'striped',
      totalsStyle: 'box',
      footerStyle: 'boxed',
      signaturePlacement: 'bottom-right',
    },
    defaultTheme: {
      primaryColor: '#059669',
      secondaryColor: '#10b981',
      textColor: '#064e3b',
      fontFamily: 'Montserrat',
    },
  },
  {
    id: 'inv-elegant-bw',
    name: 'Elegant Black & White',
    type: 'invoice',
    category: 'Classic',
    description: 'Monochrome precision layout with executive typography and thin borders.',
    style: 'Monochrome • Premium',
    previewColor: '#000000',
    layout: {
      headerStyle: 'minimal',
      tableStyle: 'clean',
      totalsStyle: 'subtle',
      footerStyle: 'simple',
      signaturePlacement: 'bottom-right',
    },
    defaultTheme: {
      primaryColor: '#000000',
      secondaryColor: '#525252',
      textColor: '#171717',
      fontFamily: 'Lato',
    },
  },
  {
    id: 'inv-geometric',
    name: 'Modern Geometric',
    type: 'invoice',
    category: 'Creative',
    description: 'Geometric header element grid with distinct visual hierarchy blocks.',
    style: 'Creative • Grid',
    previewColor: '#7c3aed',
    layout: {
      headerStyle: 'split',
      tableStyle: 'bordered',
      totalsStyle: 'bold-banner',
      footerStyle: 'boxed',
      signaturePlacement: 'bottom-right',
    },
    defaultTheme: {
      primaryColor: '#7c3aed',
      secondaryColor: '#8b5cf6',
      textColor: '#1e1b4b',
      fontFamily: 'Poppins',
    },
  },
  {
    id: 'inv-service',
    name: 'Service Invoice',
    type: 'invoice',
    category: 'Service',
    description: 'Optimized for service providers, consultants, agencies, and hourly rates.',
    style: 'Services • Hourly',
    previewColor: '#0284c7',
    layout: {
      headerStyle: 'clean',
      tableStyle: 'clean',
      totalsStyle: 'box',
      footerStyle: 'simple',
      signaturePlacement: 'bottom-right',
    },
    defaultTheme: {
      primaryColor: '#0284c7',
      secondaryColor: '#38bdf8',
      textColor: '#0c4a6e',
      fontFamily: 'Open Sans',
    },
  },
  {
    id: 'inv-retail',
    name: 'Retail Itemized',
    type: 'invoice',
    category: 'Retail',
    description: 'Optimized for many line items with SKU, barcode, unit, and item discounts.',
    style: 'Retail • Multi-Item',
    previewColor: '#d97706',
    layout: {
      headerStyle: 'classic',
      tableStyle: 'compact',
      totalsStyle: 'right-aligned',
      footerStyle: 'simple',
      signaturePlacement: 'bottom-right',
    },
    defaultTheme: {
      primaryColor: '#d97706',
      secondaryColor: '#f59e0b',
      textColor: '#451a03',
      fontFamily: 'Roboto',
    },
  },
  {
    id: 'inv-premium',
    name: 'Premium Executive',
    type: 'invoice',
    category: 'Premium',
    description: 'Executive navy & gold styling with dedicated signature & stamp placement.',
    style: 'Executive • High Value',
    previewColor: '#0f172a',
    badgeText: 'Executive',
    layout: {
      headerStyle: 'executive',
      tableStyle: 'accent-header',
      totalsStyle: 'bold-banner',
      footerStyle: 'executive',
      signaturePlacement: 'bottom-split',
    },
    defaultTheme: {
      primaryColor: '#0f172a',
      secondaryColor: '#b45309',
      textColor: '#0f172a',
      fontFamily: 'Montserrat',
    },
  },
];
