import { DocumentTemplate } from '../types/template';

export const QUOTATION_TEMPLATES: DocumentTemplate[] = [
  {
    id: 'qt-classic',
    name: 'Classic Business',
    type: 'quotation',
    category: 'Classic',
    description: 'Traditional formal quotation format with project scope and validity terms.',
    style: 'Classic • Proposal',
    previewColor: '#1e293b',
    layout: {
      headerStyle: 'classic',
      tableStyle: 'bordered',
      totalsStyle: 'box',
      footerStyle: 'simple',
      signaturePlacement: 'bottom-right',
    },
    defaultTheme: {
      primaryColor: '#1e293b',
      secondaryColor: '#64748b',
      textColor: '#0f172a',
      fontFamily: 'Inter',
    },
  },
  {
    id: 'qt-minimal',
    name: 'Minimal Professional',
    type: 'quotation',
    category: 'Minimal',
    description: 'Clean and simple estimate format with thin dividers and high readability.',
    style: 'Minimal • Estimate',
    previewColor: '#475569',
    layout: {
      headerStyle: 'minimal',
      tableStyle: 'clean',
      totalsStyle: 'subtle',
      footerStyle: 'simple',
      signaturePlacement: 'bottom-right',
    },
    defaultTheme: {
      primaryColor: '#475569',
      secondaryColor: '#94a3b8',
      textColor: '#1e293b',
      fontFamily: 'Roboto',
    },
  },
  {
    id: 'qt-modern-blue',
    name: 'Modern Blue Proposal',
    type: 'quotation',
    category: 'Modern',
    description: 'Corporate blue visual identity with rounded container cards and clear grand total.',
    style: 'Modern • Blue Accent',
    previewColor: '#2563eb',
    badgeText: 'Popular',
    layout: {
      headerStyle: 'modern',
      tableStyle: 'striped',
      totalsStyle: 'box',
      footerStyle: 'boxed',
      signaturePlacement: 'bottom-right',
    },
    defaultTheme: {
      primaryColor: '#2563eb',
      secondaryColor: '#3b82f6',
      textColor: '#0f172a',
      fontFamily: 'Poppins',
    },
  },
  {
    id: 'qt-monochrome',
    name: 'Black & White',
    type: 'quotation',
    category: 'Classic',
    description: 'Crisp black and white proposal design suitable for formal corporate bids.',
    style: 'Monochrome • B2B',
    previewColor: '#000000',
    layout: {
      headerStyle: 'minimal',
      tableStyle: 'clean',
      totalsStyle: 'subtle',
      footerStyle: 'simple',
      signaturePlacement: 'bottom-right',
    },
    defaultTheme: {
      primaryColor: '#000000',
      secondaryColor: '#525252',
      textColor: '#171717',
      fontFamily: 'Lato',
    },
  },
  {
    id: 'qt-green',
    name: 'Green Modern',
    type: 'quotation',
    category: 'Modern',
    description: 'Modern green business design with prominent validity and terms card.',
    style: 'Fresh • Modern',
    previewColor: '#059669',
    layout: {
      headerStyle: 'modern',
      tableStyle: 'striped',
      totalsStyle: 'box',
      footerStyle: 'boxed',
      signaturePlacement: 'bottom-right',
    },
    defaultTheme: {
      primaryColor: '#059669',
      secondaryColor: '#10b981',
      textColor: '#064e3b',
      fontFamily: 'Montserrat',
    },
  },
  {
    id: 'qt-creative',
    name: 'Creative Agency Proposal',
    type: 'quotation',
    category: 'Creative',
    description: 'Bold typography and creative accents for marketing, software & design proposals.',
    style: 'Creative • Agency',
    previewColor: '#7c3aed',
    badgeText: 'Agency',
    layout: {
      headerStyle: 'split',
      tableStyle: 'bordered',
      totalsStyle: 'bold-banner',
      footerStyle: 'boxed',
      signaturePlacement: 'bottom-right',
    },
    defaultTheme: {
      primaryColor: '#7c3aed',
      secondaryColor: '#8b5cf6',
      textColor: '#1e1b4b',
      fontFamily: 'Poppins',
    },
  },
  {
    id: 'qt-construction',
    name: 'Construction & Project Estimate',
    type: 'quotation',
    category: 'Service',
    description: 'Breakdown of materials, labor, scope of work, and project milestones.',
    style: 'Project • Construction',
    previewColor: '#d97706',
    layout: {
      headerStyle: 'classic',
      tableStyle: 'bordered',
      totalsStyle: 'box',
      footerStyle: 'executive',
      signaturePlacement: 'bottom-split',
    },
    defaultTheme: {
      primaryColor: '#d97706',
      secondaryColor: '#f59e0b',
      textColor: '#451a03',
      fontFamily: 'Roboto',
    },
  },
  {
    id: 'qt-product',
    name: 'Product Sales Quotation',
    type: 'quotation',
    category: 'Retail',
    description: 'Optimized for product catalog quotes with SKU, unit prices, and bulk volume discounts.',
    style: 'Product • Wholesale',
    previewColor: '#0284c7',
    layout: {
      headerStyle: 'clean',
      tableStyle: 'compact',
      totalsStyle: 'right-aligned',
      footerStyle: 'simple',
      signaturePlacement: 'bottom-right',
    },
    defaultTheme: {
      primaryColor: '#0284c7',
      secondaryColor: '#38bdf8',
      textColor: '#0c4a6e',
      fontFamily: 'Open Sans',
    },
  },
  {
    id: 'qt-service',
    name: 'Service Proposal',
    type: 'quotation',
    category: 'Service',
    description: 'Service duration, deliverables, scope, and retainership fee structure.',
    style: 'Retainer • Service',
    previewColor: '#0f766e',
    layout: {
      headerStyle: 'clean',
      tableStyle: 'clean',
      totalsStyle: 'box',
      footerStyle: 'simple',
      signaturePlacement: 'bottom-right',
    },
    defaultTheme: {
      primaryColor: '#0f766e',
      secondaryColor: '#14b8a6',
      textColor: '#134e4a',
      fontFamily: 'Inter',
    },
  },
  {
    id: 'qt-premium',
    name: 'Premium Corporate Bid',
    type: 'quotation',
    category: 'Premium',
    description: 'High-end executive proposal format with corporate terms, scope, and dual signatures.',
    style: 'Executive • Proposal',
    previewColor: '#0f172a',
    badgeText: 'Executive',
    layout: {
      headerStyle: 'executive',
      tableStyle: 'accent-header',
      totalsStyle: 'bold-banner',
      footerStyle: 'executive',
      signaturePlacement: 'bottom-split',
    },
    defaultTheme: {
      primaryColor: '#0f172a',
      secondaryColor: '#b45309',
      textColor: '#0f172a',
      fontFamily: 'Montserrat',
    },
  },
];
