import { TemplateTheme } from './types';

export const QUOTATION_THEMES: Record<string, TemplateTheme> = {
  emerald: {
    id: 'emerald',
    name: 'VISTAAR Emerald',
    primaryColor: '#059669',
    secondaryColor: '#10b981',
    accentColor: '#d1fae5',
    textColor: '#064e3b',
    backgroundColor: '#ffffff',
    cardBg: '#f0fdf4',
    borderColor: '#a7f3d0',
    fontFamily: 'Inter',
  },
  corporate: {
    id: 'corporate',
    name: 'Corporate Blue',
    primaryColor: '#2563eb',
    secondaryColor: '#3b82f6',
    accentColor: '#dbeafe',
    textColor: '#0f172a',
    backgroundColor: '#ffffff',
    cardBg: '#eff6ff',
    borderColor: '#bfdbfe',
    fontFamily: 'Inter',
  },
  navy: {
    id: 'navy',
    name: 'Executive Navy',
    primaryColor: '#0f172a',
    secondaryColor: '#334155',
    accentColor: '#f1f5f9',
    textColor: '#0f172a',
    backgroundColor: '#ffffff',
    cardBg: '#f8fafc',
    borderColor: '#cbd5e1',
    fontFamily: 'Montserrat',
  },
  charcoal: {
    id: 'charcoal',
    name: 'Charcoal Modern',
    primaryColor: '#18181b',
    secondaryColor: '#3f3f46',
    accentColor: '#f4f4f5',
    textColor: '#09090b',
    backgroundColor: '#ffffff',
    cardBg: '#fafafa',
    borderColor: '#e4e4e7',
    fontFamily: 'Roboto',
  },
  slate: {
    id: 'slate',
    name: 'Slate Teal',
    primaryColor: '#0f766e',
    secondaryColor: '#14b8a6',
    accentColor: '#ccfbf1',
    textColor: '#134e4a',
    backgroundColor: '#ffffff',
    cardBg: '#f0fdfa',
    borderColor: '#99f6e4',
    fontFamily: 'Poppins',
  },
  forest: {
    id: 'forest',
    name: 'Forest Deep',
    primaryColor: '#14532d',
    secondaryColor: '#166534',
    accentColor: '#dcfce7',
    textColor: '#052e16',
    backgroundColor: '#ffffff',
    cardBg: '#f0fdf4',
    borderColor: '#bbf7d0',
    fontFamily: 'Lato',
  },
  burgundy: {
    id: 'burgundy',
    name: 'Royal Burgundy',
    primaryColor: '#881337',
    secondaryColor: '#9f1239',
    accentColor: '#ffe4e6',
    textColor: '#4c0519',
    backgroundColor: '#ffffff',
    cardBg: '#fff1f2',
    borderColor: '#fecdd3',
    fontFamily: 'Playfair Display',
  },
  mono: {
    id: 'mono',
    name: 'Minimal Mono',
    primaryColor: '#000000',
    secondaryColor: '#525252',
    accentColor: '#f5f5f5',
    textColor: '#171717',
    backgroundColor: '#ffffff',
    cardBg: '#fafafa',
    borderColor: '#e5e5e5',
    fontFamily: 'Inter',
  },
  amber: {
    id: 'amber',
    name: 'Warm Amber',
    primaryColor: '#d97706',
    secondaryColor: '#f59e0b',
    accentColor: '#fef3c7',
    textColor: '#451a03',
    backgroundColor: '#ffffff',
    cardBg: '#fffbeb',
    borderColor: '#fde68a',
    fontFamily: 'Open Sans',
  },
  purple: {
    id: 'purple',
    name: 'Agency Purple',
    primaryColor: '#7c3aed',
    secondaryColor: '#8b5cf6',
    accentColor: '#ede9fe',
    textColor: '#1e1b4b',
    backgroundColor: '#ffffff',
    cardBg: '#f5f3ff',
    borderColor: '#ddd6fe',
    fontFamily: 'Poppins',
  },
};

export const DEFAULT_THEME = QUOTATION_THEMES.corporate;
