import { InvoiceData, BusinessData, CustomerData } from './types';
import { BrandingConfig } from '../../types/template';

export const DEMO_BUSINESS: BusinessData = {
  businessName: 'VISTAAR Business Solutions',
  legalName: 'VISTAAR Technologies Private Limited',
  ownerName: 'Rajesh Kumar',
  phone: '+91 98765 43210',
  email: 'billing@vistaar.app',
  website: 'https://vistaar.app',
  address: 'Plot 42, Tech Park Sector 5',
  addressLine2: 'Powai Industrial Area',
  city: 'Mumbai',
  state: 'Maharashtra',
  pincode: '400076',
  country: 'India',
  gstin: '27AAAAA0000A1Z5',
  pan: 'ABCDE1234F',
  bankDetails: {
    bankName: 'HDFC Bank Ltd.',
    accountHolder: 'VISTAAR Technologies Pvt Ltd',
    accountNo: '50200012345678',
    ifscCode: 'HDFC0000240',
    branch: 'Powai Branch',
    upiId: 'vistaar@hdfcbank',
  },
};

export const DEMO_CUSTOMER: CustomerData = {
  id: 'cust-demo-01',
  name: 'Apex Enterprises Pvt Ltd',
  phone: '+91 98200 11223',
  whatsapp: '+91 98200 11223',
  email: 'accounts@apexenterprises.in',
  address: 'Suite 802, Synergy Towers, BKC',
  city: 'Mumbai',
  state: 'Maharashtra',
  pincode: '400051',
  gstin: '27AAACA9999B1Z2',
};

export const DEMO_INVOICE: InvoiceData = {
  invoiceNumber: 'INV-2026-089',
  date: '2026-08-29',
  dueDate: '2026-09-15',
  referenceNumber: 'PO-2026-7741',
  paymentStatus: 'PARTIALLY_PAID',
  currency: '₹',
  items: [
    {
      id: 'demo-inv-item-1',
      productName: 'Enterprise ERP Management Software License',
      sku: 'SW-ERP-PRO',
      unit: 'License',
      quantity: 1,
      buyPrice: 30000,
      sellingPrice: 45000,
      discountAmount: 2500,
      taxPercent: 18,
      taxAmount: 7650,
      total: 50150,
    },
    {
      id: 'demo-inv-item-2',
      productName: 'Cloud Server Infrastructure Setup & Optimization',
      sku: 'SRV-CLOUD-SETUP',
      unit: 'Hours',
      quantity: 15,
      buyPrice: 1200,
      sellingPrice: 2000,
      discountAmount: 1500,
      taxPercent: 18,
      taxAmount: 5130,
      total: 33630,
    },
    {
      id: 'demo-inv-item-3',
      productName: 'Annual Dedicated Technical Support Retainer',
      sku: 'SUP-ANNUAL-PRO',
      unit: 'Month',
      quantity: 12,
      buyPrice: 800,
      sellingPrice: 1500,
      discountAmount: 0,
      taxPercent: 18,
      taxAmount: 3240,
      total: 21240,
    },
  ],
  subtotal: 93000,
  discountTotal: 4000,
  taxTotal: 16020,
  grandTotal: 105020,
  paidAmount: 50000,
  balanceAmount: 55020,
  notes: 'Payment due within 15 days of invoice date. Thank you for your business!',
  terms: '1. All payments should be made via NEFT/RTGS/UPI to the bank account specified.\n2. Interest @ 18% p.a. will be charged on overdue payments.\n3. Goods/services once delivered are non-refundable.',
  footerText: 'This is a computer-generated tax invoice and requires no physical signature.',
};

export const DEMO_BRANDING: BrandingConfig = {
  logoAlignment: 'left',
  logoScale: 1,
  signatureScale: 1,
  stampScale: 1,
};
