import { InvoiceTemplateTheme } from './types';

export const INVOICE_THEMES: Record<string, InvoiceTemplateTheme> = {
  'corporate-navy': {
    id: 'corporate-navy',
    name: 'Corporate Navy',
    primaryColor: '#1e293b',
    secondaryColor: '#334155',
    textColor: '#0f172a',
    accentColor: '#2563eb',
    backgroundColor: '#ffffff',
    fontFamily: 'Inter',
  },
  'executive-pro': {
    id: 'executive-pro',
    name: 'Executive Pro',
    primaryColor: '#0f172a',
    secondaryColor: '#1e293b',
    textColor: '#0f172a',
    accentColor: '#d97706',
    backgroundColor: '#ffffff',
    fontFamily: 'Montserrat',
  },
  'modern-blue': {
    id: 'modern-blue',
    name: 'Modern Blue',
    primaryColor: '#2563eb',
    secondaryColor: '#3b82f6',
    textColor: '#0f172a',
    accentColor: '#60a5fa',
    backgroundColor: '#ffffff',
    fontFamily: 'Poppins',
  },
  'emerald-pro': {
    id: 'emerald-pro',
    name: 'Emerald Pro',
    primaryColor: '#059669',
    secondaryColor: '#10b981',
    textColor: '#064e3b',
    accentColor: '#34d399',
    backgroundColor: '#ffffff',
    fontFamily: 'Roboto',
  },
  'crimson-luxury': {
    id: 'crimson-luxury',
    name: 'Crimson Luxury',
    primaryColor: '#991b1b',
    secondaryColor: '#dc2626',
    textColor: '#450a0a',
    accentColor: '#f87171',
    backgroundColor: '#ffffff',
    fontFamily: 'Inter',
  },
  'slate-gold': {
    id: 'slate-gold',
    name: 'Slate Gold',
    primaryColor: '#1e1b4b',
    secondaryColor: '#312e81',
    textColor: '#0f172a',
    accentColor: '#b45309',
    backgroundColor: '#ffffff',
    fontFamily: 'Playfair Display',
  },
  'minimal-mono': {
    id: 'minimal-mono',
    name: 'Minimal Mono',
    primaryColor: '#18181b',
    secondaryColor: '#3f3f46',
    textColor: '#09090b',
    accentColor: '#71717a',
    backgroundColor: '#ffffff',
    fontFamily: 'Inter',
  },
  'purple-agency': {
    id: 'purple-agency',
    name: 'Purple Agency',
    primaryColor: '#7c3aed',
    secondaryColor: '#8b5cf6',
    textColor: '#1e1b4b',
    accentColor: '#c084fc',
    backgroundColor: '#ffffff',
    fontFamily: 'Poppins',
  },
};

export const defaultInvoiceThemes = INVOICE_THEMES;
export const DEFAULT_INVOICE_THEME: InvoiceTemplateTheme = INVOICE_THEMES['modern-blue'];
